### ISSUE TITLE
Test and improve the performance of OSX builds with containers

### ISSUE THREAD

**Issue by nictuku** [yourbase/yb#28]
Now that we are moving to build with containers by default, OSX builds will suffer from slow file access in mounted volumes: https://github.com/docker/for-mac/issues/77

This might help: https://docs.docker.com/docker-for-mac/osxfs-caching/ (thanks David W)

**Comment by zombiezen** [comment]
Closing this out due to [findings in #266](https://github.com/yourbase/yb/pull/266#issuecomment-745580237).
